"""add items column to orders

Revision ID: 38d8a6f4ad09
Revises: 34495cf1f44d
Create Date: 2025-10-09 22:50:21.426566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d8a6f4ad09'
down_revision: Union[str, Sequence[str], None] = '34495cf1f44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'itens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('itens', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
